### PR TITLE
E sound

### PR DESCRIPTION
**Pull request by CODman-2019**
SFX and Music implemented

### CODE REVIEW

**Review by CODman-2019 — COMMENTED** [review]
just added wav files and script modifications. 
Note: please remove the Sound Manager, It was originally goin to be used for managing sound but it was no longer needed

**Comment by seromyr** [comment]
> just added wav files and script modifications.
> Note: please remove the Sound Manager, It was originally goin to be used for managing sound but it was no longer needed

You have to resolve the file yourselves Esam. It's your responsibility

**Review by CODman-2019 — COMMENTED** [review]
Still figuring out conflicts

**Comment by seromyr** [comment]
> Still figuring out conflicts

Let me help you out this time.

Next time, please remember don't commit files that you didn't work on.

**Comment by CODman-2019** [comment]
Thing is that some of the files that appeared, I never even touched or even know about, like the png files.

**Comment by CODman-2019** [comment]
here comes the process of removing a lot of files

**Comment by CODman-2019** [comment]
X   X
_____
 |__|
Meant to be a dead face with tongue out

**Comment by seromyr** [comment]
meta files are data files generated by Unity to store the imported settings. You can ignore them.

Anyway, I've just resolved conflicts for you. Please check your branch integrity.

**Review by seromyr — APPROVED** [review]

**Review by seromyr — APPROVED** [review]

**Comment by seromyr** [comment]
@CODman-2019  I fixed conflicted for you. Please merge your things.

**Pull request merged**
